load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

RULES_JVM_EXTERNAL_TAG = "5.3"

RULES_JVM_EXTERNAL_SHA = "d31e369b854322ca5098ea12c69d7175ded971435e55c18dd9dd5f29cc5249ac"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/%s/rules_jvm_external-%s.tar.gz" % (RULES_JVM_EXTERNAL_TAG, RULES_JVM_EXTERNAL_TAG),
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

maybe(
    http_archive,
    name = "bazel_skylib",
    sha256 = "1c531376ac7e5a180e0237938a2536de0c54d93f5c278634818e0efc952dd56c",
    urls = [
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

local_repository(
    name = "rules_android",
    path = "../..",  # rules_android's WORKSPACE relative to this inner workspace
)

load("@rules_android//:prereqs.bzl", "rules_android_prereqs")

rules_android_prereqs()

load("@rules_android//:defs.bzl", "rules_android_workspace")

rules_android_workspace()

load("@rules_android//rules:rules.bzl", "android_sdk_repository")

android_sdk_repository(
    name = "androidsdk",
)

register_toolchains(
    "@rules_android//toolchains/android:android_default_toolchain",
    "@rules_android//toolchains/android_sdk:android_sdk_tools",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    name = "example_deps",
    aar_import_bzl_label = "@rules_android//rules:rules.bzl",
    artifacts = [
        # LeakCanary
        "com.squareup.leakcanary:leakcanary-android-core:aar:2.12",
        "com.squareup.leakcanary:leakcanary-android-instrumentation:aar:2.12",
        "com.squareup.leakcanary:leakcanary-android-utils:aar:2.12",
        "com.squareup.leakcanary:leakcanary-android:aar:2.12",
        "com.squareup.leakcanary:leakcanary-object-watcher-android-androidx:aar:2.12",
        "com.squareup.leakcanary:leakcanary-object-watcher-android-core:aar:2.12",
        "com.squareup.leakcanary:leakcanary-object-watcher-android-support-fragments:aar:2.12",
        "com.squareup.leakcanary:leakcanary-object-watcher-android:aar:2.12",
        "com.squareup.leakcanary:leakcanary-object-watcher:jar:2.12",
        "com.squareup.leakcanary:plumber-android-core:aar:2.12",
        "com.squareup.leakcanary:plumber-android:aar:2.12",
        "com.squareup.leakcanary:shark-android:jar:2.12",
        "com.squareup.leakcanary:shark-graph:jar:2.12",
        "com.squareup.leakcanary:shark-hprof:jar:2.12",
        "com.squareup.leakcanary:shark-log:jar:2.12",
        "com.squareup.leakcanary:shark:jar:2.12",
        # AndroidX
        "androidx.lifecycle:lifecycle-viewmodel-ktx:aar:2.6.2",
        "androidx.lifecycle:lifecycle-viewmodel-savedstate:aar:2.6.2",
        "androidx.lifecycle:lifecycle-viewmodel:aar:2.6.2",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    use_starlark_android_rules = True,
)
